version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    image: project-image:1.0.0
    container_name: 'project-container'
    volumes:
      - ./:/project-folder
    ports:
      - 8080:8080
    networks:
      - project-network
    environment:
      - API_HOST=http://localhost
      - API_PORT=8080

networks:
  project-network:
    name: project-page-network
